### ISSUE TITLE
Mac OS X 10.11 Error: compile of ' "src/MxArray.cpp" ' failed.

### ISSUE THREAD

**Issue by Sandbox3aster** [kyamagu/mexopencv#222]
I get the following error when trying to compile mexopencv on OS X 10.11 on a Retina Macbook Pro 2015 with MATLAB 2014b, and i did clean before every recompiling.

```
Charless-MacBook-Pro:mexopencv Charles$ make MATLABDIR=/Applications/MATLAB_R2014b.app
/Applications/MATLAB_R2014b.app/bin/mex -c -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -outdir lib src/MxArray.cpp
src/MxArray.cpp:621:25: error: non-constant-expression cannot be narrowed from
      type 'mwSize' (aka 'unsigned long') to 'int' in initializer list
      [-Wc++11-narrowing]
    const int dims[] = {m, n};
                        ^
src/MxArray.cpp:621:25: note: insert an explicit cast to silence this issue
    const int dims[] = {m, n};
                        ^
                        static_cast<int>( )
src/MxArray.cpp:621:28: error: non-constant-expression cannot be narrowed from
      type 'mwSize' (aka 'unsigned long') to 'int' in initializer list
      [-Wc++11-narrowing]
    const int dims[] = {m, n};
                           ^
src/MxArray.cpp:621:28: note: insert an explicit cast to silence this issue
    const int dims[] = {m, n};
                           ^
                           static_cast<int>( )
2 errors generated.

    mex: compile of ' "src/MxArray.cpp"' failed.

make: *** [lib/MxArray.o] Error 255
```

Before compiling i looked through the mex configuration for Matlab 2011a [here](https://gist.github.com/kyamagu/8363310) as reference, i think there might be something wrong with **mexopts.sh** which i edited as followed:

```
# mexopts.sh	Shell script for configuring MEX-file creation script,
#               mex.  These options were tested with the specified compiler.
#
# usage:        Do not call this file directly; it is sourced by the
#               mex shell script.  Modify only if you don't like the
#               defaults after running mex.  No spaces are allowed
#               around the '=' in the variable assignment.
#
# Note: For the version of system compiler supported with this release,
#       refer to the Supported and Compatible Compiler List at:
#       http://www.mathworks.com/support/compilers/current_release/
#
#
# SELECTION_TAGs occur in template option files and are used by MATLAB
# tools, such as mex and mbuild, to determine the purpose of the contents
# of an option file. These tags are only interpreted when preceded by '#'
# and followed by ':'.
#
#SELECTION_TAG_MEX_OPT: Template Options file for building MEX-files
#
# Copyright 1984-2011 The MathWorks, Inc.
#----------------------------------------------------------------------------
#
    TMW_ROOT="$MATLAB"
    MFLAGS=''
    if [ "$ENTRYPOINT" = "mexLibrary" ]; then
        MLIBS="-L$TMW_ROOT/bin/$Arch -lmx -lmex -lmat -lmwservices -lut"
    else  
        MLIBS="-L$TMW_ROOT/bin/$Arch -lmx -lmex -lmat"
    fi
    case "$Arch" in
        Undetermined)
#----------------------------------------------------------------------------
# Change this line if you need to specify the location of the MATLAB
# root directory.  The script needs to know where to find utility
# routines so that it can determine the architecture; therefore, this
# assignment needs to be done while the architecture is still
# undetermined.
#----------------------------------------------------------------------------
            MATLAB="$MATLAB"
            ;;
        glnx86)
#----------------------------------------------------------------------------
echo "Error: Did not imbed 'options.sh' code"; exit 1 #imbed options.sh glnx86 12
#----------------------------------------------------------------------------
            ;;
        glnxa64)
#----------------------------------------------------------------------------
            RPATH="-Wl,-rpath-link,$TMW_ROOT/bin/$Arch"
            # StorageVersion: 1.0
            # CkeyName: GNU C
            # CkeyManufacturer: GNU
            # CkeyLanguage: C
            # CkeyVersion:
            # CkeyLinkerName: GNU ld
            # CkeyLinkerVersion:
            CC='gcc'
            CFLAGS='-ansi -D_GNU_SOURCE'
            CFLAGS="$CFLAGS  -fexceptions"
            CFLAGS="$CFLAGS -fPIC -fno-omit-frame-pointer -pthread"
            CLIBS="$RPATH $MLIBS -lm"
            COPTIMFLAGS='-O -DNDEBUG'
            CDEBUGFLAGS='-g'
            CLIBS="$CLIBS -lstdc++"
#
            # C++keyName: GNU C++
            # C++keyManufacturer: GNU
            # C++keyLanguage: C++
            # C++keyVersion:
            # C++keyLinkerName: GNU ld
            # C++keyLinkerVersion:  
            CXX='g++'
            CXXFLAGS='-ansi -D_GNU_SOURCE'
            CXXFLAGS="$CXXFLAGS -fPIC -fno-omit-frame-pointer -pthread"
            CXXLIBS="$RPATH $MLIBS -lm"
            CXXOPTIMFLAGS='-O -DNDEBUG'
            CXXDEBUGFLAGS='-g'
#
            # FortrankeyName: gfortran
            # FortrankeyManufacturer: GNU
            # FortrankeyLanguage: Fortran
            # FortrankeyVersion:
            # FortrankeyLinkerName: GNU ld
            # FortrankeyLinkerVersion:  
#
            FC='gfortran'
            FFLAGS='-fexceptions -fbackslash'
            FFLAGS="$FFLAGS -fPIC -fno-omit-frame-pointer"
            FLIBS="$RPATH $MLIBS -lm"
            FOPTIMFLAGS='-O'
            FDEBUGFLAGS='-g'
#
            LD="$COMPILER"
            LDEXTENSION='.mexa64'
            LDFLAGS="-pthread -shared -Wl,--version-script,$TMW_ROOT/extern/lib/$Arch/$MAPFILE -Wl,--no-undefined"
            LDOPTIMFLAGS='-O'
            LDDEBUGFLAGS='-g'
#
            POSTLINK_CMDS=':'
#----------------------------------------------------------------------------
            ;;
        sol64)
#----------------------------------------------------------------------------
echo "Error: Did not imbed 'options.sh' code"; exit 1 #imbed options.sh sol64 12
#----------------------------------------------------------------------------
            ;;
        mac)
#----------------------------------------------------------------------------
echo "Error: Did not imbed 'options.sh' code"; exit 1 #imbed options.sh mac 12
#----------------------------------------------------------------------------
            ;;
        maci)
#----------------------------------------------------------------------------
echo "Error: Did not imbed 'options.sh' code"; exit 1 #imbed options.sh maci 12
#----------------------------------------------------------------------------
            ;;
        maci64)
#----------------------------------------------------------------------------
            # StorageVersion: 1.0
            # CkeyName: Clang
            # CkeyManufacturer: Apple
            # CkeyLanguage: C
            # CkeyVersion:
            # CkeyLinkerName:
            # CkeyLinkerVersion:
            CC='clang'
## workaround clang defect temporarily use line below           SDKROOT='/Developer/SDKs/MacOSX10.6.sdk'
# compute SDK root on the fly
# target 10.8
            MW_SDKROOT_TMP="find `xcode-select -print-path` -name MacOSX10.11.sdk"
			MW_SDKROOT='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/'
            MACOSX_DEPLOYMENT_TARGET='10.11'
            ARCHS='x86_64'
            CFLAGS="-fno-common -arch $ARCHS -isysroot $MW_SDKROOT -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET"
            CFLAGS="$CFLAGS  -fexceptions"
            CFLAGS="$CFLAGS -Dchar16_t=uint16_t"
            CLIBS="$MLIBS"
            COPTIMFLAGS='-O2 -DNDEBUG'
            CDEBUGFLAGS='-g'
#
            CLIBS="$CLIBS -lstdc++"
            # C++keyName: Clang++
            # C++keyManufacturer: Apple
            # C++keyLanguage: C++
            # C++keyVersion:
            # C++keyLinkerName:
            # C++keyLinkerVersion:
            CXX='clang++'
            CXXFLAGS="-fno-common -fexceptions -arch $ARCHS -isysroot $MW_SDKROOT -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET"
            CXXFLAGS="$CXXFLAGS -std=c++11 -stdlib=libc++"
            CXXLIBS="$MLIBS -lc++"
            CXXOPTIMFLAGS='-O2 -DNDEBUG'
            CXXDEBUGFLAGS='-g'
#
            # FortrankeyName: GNU Fortran
            # FortrankeyManufacturer: GNU
            # FortrankeyLanguage: Fortran
            # FortrankeyVersion: 
            # FortrankeyLinkerName: 
            # FortrankeyLinkerVersion:
            FC='gfortran'
            FFLAGS='-fexceptions -m64 -fbackslash'
            FC_LIBDIR=`$FC -print-file-name=libgfortran.dylib 2>&1 | sed -n '1s/\/*libgfortran\.dylib//p'`
            FC_LIBDIR2=`$FC -print-file-name=libgfortranbegin.a 2>&1 | sed -n '1s/\/*libgfortranbegin\.a//p'`
            FLIBS="$MLIBS -L$FC_LIBDIR -lgfortran -L$FC_LIBDIR2 -lgfortranbegin"
            FOPTIMFLAGS='-O'
            FDEBUGFLAGS='-g'
#
            LD="$CC"
            LDEXTENSION='.mexmaci64'
            LDFLAGS="-arch $ARCHS -Wl,-syslibroot,$MW_SDKROOT -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET"
            LDFLAGS="$LDFLAGS -bundle -Wl,-exported_symbols_list,$TMW_ROOT/extern/lib/$Arch/$MAPFILE"
            LDOPTIMFLAGS='-O'
            LDDEBUGFLAGS='-g'
#
            POSTLINK_CMDS=':'
#----------------------------------------------------------------------------
            ;;
    esac

```

I'd be appreciated if anyone could do help on this cause my thesis is counting on this:)

Best Regards
Charles Wu

**Comment by amroamroamro** [comment]
see this fix: https://github.com/kyamagu/mexopencv/issues/219#issuecomment-162692343

**Comment by Sandbox3aster** [comment]
@amroamroamro sry about replying so late, i tried the method in https://github.com/kyamagu/mexopencv/issues/219#issuecomment-162692343 and got a new error
```
Charless-MacBook-Pro:mexopencv Charles$ make MATLABDIR=/Applications/MATLAB_R2014b.app
/Applications/MATLAB_R2014b.app/bin/mex -c -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -outdir lib src/MxArray.cpp
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
/Applications/MATLAB_R2014b.app/bin/mex -c -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -outdir lib src/mexopencv_features2d.cpp
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
/Applications/MATLAB_R2014b.app/bin/mex -c -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -outdir lib src/mexopencv_ml.cpp
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
ar -crs lib/libMxArray.a lib/MxArray.o lib/mexopencv_features2d.o lib/mexopencv_ml.o
/Applications/MATLAB_R2014b.app/bin/mex -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -output +cv/AGAST src/+cv/AGAST.cpp -Llib -lMxArray -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lippicv -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core  
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
ld: library not found for -lippicv
clang: error: linker command failed with exit code 1 (use -v to see invocation)

    mex: link of ' "+cv/AGAST.mexmaci64"' failed.

make: *** [+cv/AGAST.mexmaci64] Error 255
```
and when i run:
```
pkg-config --cflags --libs opencv
```
it shows that:
```
-I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lippicv -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core
```
does it has anything to do with messing up opencv and opencv3? i think there might be other causes.

**Comment by amroamroamro** [comment]
That's a linking issue; `ippicv` is Intel IPP library (to be exact it's a free subset of the library specifically for OpenCV). The library is an optional optimization but I think that IPP-ICV should be [downloaded](https://github.com/Itseez/opencv/tree/master/3rdparty/ippicv) by default by the CMake build scripts on supported platforms. I'm not very familiar with homebrew stuff, so try recompiling opencv from source this time using the explicit `-DWITH_IPP=ON` cmake option.

That said we're still working on updating mexopencv for OpenCV 3.1.0 support, so some functions/classes will fail to build at the moment. The current mexopencv targets OpenCV 3.0.0 instead...

**Comment by Sandbox3aster** [comment]
Thanks a lot, i tried recompiling opencv using -DWITH_IPP=ON, but still getting the same Error, did i do the thing right? i used those code while compiling opencv, didn't use homebrew.
```
mkdir build
cd build
cmake -G "Unix Makefiles" -DWITH_IPP=ON ..
make -j8
sudo make install
```

**Comment by amroamroamro** [comment]
Yes that looks correct.

Perhaps then try to disable IPP-ICV with `-DWITH_IPP=OFF`? Like I said the library is optional, and the code will fall back to the regular implementations of the image processing and computer vision functions.

If not, a quick fix could be to edit the installed `opencv.pc` pkg-config file, and add the necessary path for the compiler to find IPP-ICV, i.e `-L/path/to -lippicv` pointing to whatever location where ippicv was installed (there should be a file like `libippicv.a` somewhere).

Either way, this sounds like a possible bug in the build scripts that should be reported to OpenCV as it's not specific to mexopencv...

Let me just remind you that currently mexopencv **will not** completely build against 3.1.0. So if you need to develop with the latest mexopencv, stick with OpenCV 3.0.0 for now.

**Comment by amroamroamro** [comment]
sorry I just realized that ippicv is statically linked into opencv, so the whole `-lippicv` flag is unnecessary here! Simply remove it from the final `opencv.pc`.

So when calling `pkg-config --libs --cflags opencv`, you shouldn't see any mention of ipp, even if opencv was built with the `WITH_IPP=ON` option.

**Comment by Sandbox3aster** [comment]
@amroamroamro i fix the problem by removing `-lippicv` from `opencv.pc`, but it turns out up be more errors like this
```
src/+cv/private/Utils_.cpp:32:54: error: no member named 'CPU_MMX' in namespace 'cv'; did you mean simply 'CPU_MMX'?
        s.set("MMX",            checkHardwareSupport(cv::CPU_MMX));
                                                     ^~~~~~~~~~~
                                                     CPU_MMX
/usr/local/include/opencv2/core/cvdef.h:138:5: note: 'CPU_MMX' declared here
    CPU_MMX             = 1,
    ^
```
So i'd rather use opencv 3.0.0, opencv 3.1.0 seems to be not working with this version of mex.
Btw, Does newer version of Matlab (i.e. 2016a) has better solution for Matlab using opencv library? i'm using 2014b right now

**Comment by amroamroamro** [comment]
yes that's the 3.0.0 vs 3.1.0 part I mentioned before. This has nothing to do with your MATLAB version, it's just that there were a few changes between the two OpenCV versions, and we (mexopencv) haven't caught up just yet, though a fix is coming very soon :)

So keep using OpenCV 3.0.0 for the moment.

**Comment by amroamroamro** [comment]
@Sandbox3aster 
done! we've updated mexopencv to target opencv 3.1.0
(including the `static_cast` fix above).

Pull the latest master branch and recompile if you want to work with the latest 3.1.0 version.

**Comment by Sandbox3aster** [comment]
@amroamroamro 
I tried out the updated version the other day, but unfortunately still getting some errors, i used opencv-3.1.0
```
src/mexopencv_shape.cpp:20:49: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",           string(typeid(*p).name()));
                                                ^
src/mexopencv_shape.cpp:41:64: warning: expression with side effects will be evaluated despite being used as an operand
      to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",                          string(typeid(*p).name()));
                                                               ^
2 warnings generated.
/Applications/MATLAB_R2014b.app/bin/mex -c -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -outdir lib src/mexopencv_videostab.cpp
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
src/mexopencv_videostab.cpp:73:39: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId", string(typeid(*p).name()));
                                      ^
src/mexopencv_videostab.cpp:81:43: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",     string(typeid(*p).name()));
                                          ^
src/mexopencv_videostab.cpp:97:52: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",              string(typeid(*p).name()));
                                                   ^
src/mexopencv_videostab.cpp:112:55: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",                 string(typeid(*p).name()));
                                                      ^
src/mexopencv_videostab.cpp:129:39: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId", string(typeid(*p).name()));
                                      ^
src/mexopencv_videostab.cpp:139:45: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",       string(typeid(*p).name()));
                                            ^
src/mexopencv_videostab.cpp:153:45: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",       string(typeid(*p).name()));
                                            ^
src/mexopencv_videostab.cpp:170:49: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",           string(typeid(*p).name()));
                                                ^
src/mexopencv_videostab.cpp:184:57: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",                   string(typeid(*p).name()));
                                                        ^
src/mexopencv_videostab.cpp:200:59: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",                     string(typeid(*p).name()));
                                                          ^
src/mexopencv_videostab.cpp:231:43: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",     string(typeid(*p).name()));
                                          ^
src/mexopencv_videostab.cpp:245:52: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",              string(typeid(*p).name()));
                                                   ^
src/mexopencv_videostab.cpp:278:57: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
        s.set("TypeId",                   string(typeid(*p).name()));
                                                        ^
13 warnings generated.
ar -crs lib/libMxArray.a lib/MxArray.o lib/mexopencv_features2d.o lib/mexopencv_ml.o lib/mexopencv_shape.o lib/mexopencv_videostab.o
/Applications/MATLAB_R2014b.app/bin/mex -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include -output +cv/AGAST src/+cv/AGAST.cpp -Llib -lMxArray -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lippicv -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core  
Warning: Legacy MEX infrastructure is provided for compatibility; it will be removed in a future version of MATLAB. For more information, consult the MEX release notes http://www.mathworks.com/help/matlab/release-notes.html.
ld: library not found for -lippicv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by amroamroamro** [comment]
Those are just warnings you can ignore.

It's really a linking error there at the end. Locate the `opencv.pc` pkg-config file installed by OpenCV and remove the option `-lippicv`. The IPP-ICV library is statically linked into opencv, so you dont need to link against it as a shared library.

May I ask, how did you install opencv? This is the second time it was reported here where `-lippicv` is incorrectly specified. I think it's a bug that should be reported to whatever OpenCV distribution you're using...

**Comment by kyamagu** [comment]
@Sandbox3aster Probably the reason is the broken `pkg-config` of `opencv3` package in Homebrew, as it seems the linker flag `-L/usr/local/Cellar/opencv3/3.1.0_1/share/OpenCV/3rdparty/lib/` is missing in the `pkg-config` output. The easiest fix is to create a symlink to these files inside `/usr/local/Cellar/opencv3/3.1.0_1/lib`,

    ln -s /usr/local/Cellar/opencv3/3.1.0_1/share/OpenCV/3rdparty/lib/*.a /usr/local/Cellar/opencv3/3.1.0_1/lib/

Then, setting `PKG_CONFIG_OPENCV` to `opencv3` should compile the code without a problem.

    PKG_CONFIG_OPENCV=opencv3 make

**Comment by Sandbox3aster** [comment]
@amroamroamro i fixed the problem by simply remove the `-lippicv` from `opencv.pc`, just like i did before, but this time there is no more compiling error after that, it seems to be an opencv issue and should be reported just like @oeon (https://github.com/propublica/schooner-tk/issues/10) has encountered.
Also i used the normal way to install opencv, namely
```
mkdir release 
cd release
cmake -G "Unix Makefiles" ..
make -j8
sudo make install
```
Again Thanks a lots for the update!

**Comment by Sandbox3aster** [comment]
@kyamagu I did encounter the issue before, that's why i didn't use homebrew to install opencv, thanks anyway!
