### ISSUE TITLE
Linux,opencv 3.2

### ISSUE THREAD

**Issue by MOONBEAR0703** [kyamagu/mexopencv#416]
when I type `$ make all contrib`, it shows:
```
/tmp/mex_3797357416902806_31251/Dataset_.o：in the function ‘mexFunction’:
Dataset_.cpp:(.text+0x80a9)：undefined reference to ‘cv::datasets::createDirectory(std::string const&)’
Dataset_.cpp:(.text+0x8167)：undefined reference to ‘cv::datasets::getDirList(std::string const&, std::vector<std::string, std::allocator<std::string> >&)’
Dataset_.cpp:(.text+0x8340)：undefined reference to ‘cv::datasets::split(std::string const&, std::vector<std::string, std::allocator<std::string> >&, char)’
collect2: error: ld returned 1 exit status
Makefile:171: recipe for target 'opencv_contrib/+cv/private/Dataset_.mexa64' failed
make: *** [opencv_contrib/+cv/private/Dataset_.mexa64] Error 255
```

**Comment by amroamroamro** [comment]
If you want to enable contrib modules support, you must build both opencv and opencv_contrib.

Keep in mind you must use corresponding versions, so if you're working with opencv v3.2.0, you must also use opencv_contrib v3.2.0 and the corresponding version of [mexopencv](https://github.com/kyamagu/mexopencv/tree/v3.2.0).

Refer to the wiki for build instructions:
https://github.com/kyamagu/mexopencv/wiki/Installation-%28Linux%2C-MATLAB%2C-OpenCV-3%29

If you're still having trouble, please provide further details about your setup.

**Comment by MOONBEAR0703** [comment]
Yes, I have downloaded the zip of the opencv3.2 mexopencv.But opencv3.2 was installed a week before the mexopencv. So if I don't need contrib modules support, I can omit this question,right?

**Comment by MOONBEAR0703** [comment]
So `make clean`,then `make all`,no need to `make all contrib`

**Comment by MOONBEAR0703** [comment]
@amroamroamro Hi, do I need to set environment path of the mexopencv?
`MEX-file '/media/lab324/sdc1/xy/DeepCC/src/external/mexopencv-3.2.0/+cv/private/VideoCapture_.mexa64' invalid: /usr/local/MATLAB/R2016b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version
`GLIBCXX_3.4.21' not found (required by /usr/local/opencv3.2/lib/libopencv_core.so.3.2)。`
Though in fact they exist, my matlab cannnot open them.

**Comment by amroamroamro** [comment]
Yes, simply run `make` (which is the same thing as `make all`).
Doing `make clean` is required here to remove old artifacts when you previously tried to build with opencv_contrib support.

---

> MEX-file '.../VideoCapture_.mexa64' invalid: /usr/local/MATLAB/R2016b/.../libstdc++.so.6: version GLIBCXX_3.4.21 not found (required by .../libopencv_core.so.3.2)

This error indicates conflicting libraries, you'll need to preload them (i.e use `LD_PRELOAD`).
It's explained in the wiki:
https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29#invalid-mex-file-or-segmentation-fault
